# fly.toml app configuration file generated for magma-chat on 2023-05-08T21:57:21-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "magma-chat"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
